import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientQueryProvider from "./components/ClientQueryProvider";
import {Toaster} from 'sonner'
import EventListeners from "./components/EventListner/EventListner";
import { ThemeProvider } from "./(ui)/(admin)/context/ThemeContext";
import { SidebarProvider } from "./(ui)/(admin)/context/SidebarContext";
import { StoreProvider } from "./StoreProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test Ecommerce",
  description: "Generated by prince",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
        <Toaster richColors position="bottom-left"></Toaster>
        <EventListeners/>
        <ThemeProvider>
        <ClientQueryProvider><SidebarProvider>{children}</SidebarProvider></ClientQueryProvider>
        </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
